version: "3.9"

services:


#
#  backend_dev:
#    container_name: backend_dev
#    build:
#      context: back-end-quarkus
#      dockerfile: Dockerfiledev
#    ports:
#      - "5005:5005" # for debugging
##      - "8080:8080"
#    working_dir: /back-end-quarkus
#    volumes:
#      - ./back-end-quarkus:/back-end-quarkus
#      - cache_gradle_dev:/home/appuser/.gradle
#    networks:
#      - default
#    entrypoint: ./gradlew quarkusDev -Dquarkus.http.host=0.0.0.0 --no-daemon
#    #entrypoint: ./gradlew quarkusDev -Dquarkus.http.host=0.0.0.0
#    #entrypoint: ./gradlew quarkusDev -Dquarkus.http.host=0.0.0.0 -DdebugHost=0.0.0.0 --no-daemon
#    depends_on:
#      database_dev:
#        condition: service_healthy



  frontend_dev:
    container_name: frontend_dev
    build:
      context: frontend
      dockerfile: Dockerfiledev
    ports:
      - "3000:3000"
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
      - /frontend/.next
    networks:
      - default
#    depends_on:
#      database_dev:
#        condition: service_healthy
    entrypoint: yarn dev




volumes:
  oracle-volume-db_dev:
  cache_gradle_dev:
    driver: local

networks:
  default:
    driver: bridge
